version: '3.8'
services:
  backend:
    #platform: linux/amd64
    image: "egorsverchkov/tutorials-backend:latest"
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    links:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/tutorials_db

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: