version: '3.8'
services:
  postgresdb:
    image: postgres
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db:/var/lib/postgres
    restart: unless-stopped

  backend:
    #platform: linux/amd64
    #image: client:0.0.1
    build: ./app
    restart: on-failure
    env_file: ./.env
    ports:
      - "6868:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - postgresdb
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/tutorials_db

volumes:
  db: