version: '3.8'
services:
  backend:
    #platform: linux/amd64
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "service-db:database"
#    ports:
#      - "8000:8000"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/tutorials_db

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432"
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: