name: Deploy runner
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cd into repo
        uses: actions/checkout@v3
      - name: setup Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: clean install
        run: mvn -X clean install -Dmaven.test.skip=true
#      - name: Build & push Docker image
#        uses: mr-smithers-excellent/docker-build-push@v6
#        with:
#          image: egorsverchkov/tutorials-backend
#          tags: latest
#          registry: docker.io
#          dockerfile: compose.yaml
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
#      - name: Stop and remove containers, networks
#        run: docker-compose stop
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose up
        run: docker compose up -d